name: Build Docker image

on:
  push:
    tags: ['v*']

jobs:
  build-amd:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Extract existing image metadata
        id: image-meta
        uses: docker/metadata-action@v4
        with:
          images: atendai/evolution-api

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push AMD image
        uses: docker/build-push-action@v4
        with:
          context: .
          labels: ${{ steps.image-meta.outputs.labels }}
          platforms: linux/amd64
          push: true

  build-arm:
    runs-on: buildjet-4vcpu-ubuntu-2204-arm
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Extract existing image metadata
        id: image-meta
        uses: docker/metadata-action@v4
        with:
          images: atendai/evolution-api

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ARM image
        uses: docker/build-push-action@v4
        with:
          context: .
          labels: ${{ steps.image-meta.outputs.labels }}
          platforms: linux/arm64
          push: true
